### ISSUE TITLE
Support composite primary keys

### ISSUE THREAD

**Issue by hmatinho** [sheharyarn/memento#16]
Didn't find anywhere if memento supports composite primary keys, mnesia does support it would it be possible to bring that into memento ?

**Comment by sheharyarn** [comment]
Hey @hmatinho. Memento doesn't expose an API for composite primary keys unfortunately. Composite keys aren't that commonly used with Mnesia so I don't plan on implementing this anytime soon, but feel free to send in a PR if you would really like to see this in Memento.

Also, while I know the [`bag` type](https://hexdocs.pm/memento/Memento.Table.html#module-options) isn't exactly the same thing, take a look at it. Maybe that solves your problem?

Closing this for now, will re-open it again if a lot of people ask for it.
