### ISSUE TITLE
How to persist data on disk?

### ISSUE THREAD

**Issue by yokujin** [sheharyarn/memento#3]
Maybe I did get something wrong, but how do I persist data on disk across restarts? I reread the documentation several times, tried to reuse `:mnesia.create_table` options... And nothing - data exists only in RAM or error is raised.

**Comment by sheharyarn** [comment]
Hey @yokujin,
Thank you for pointing out the documentation issue. Setting up persistence in `Mnesia` is a bit _weird_, to say the least. It involves stopping the application, creating schemas on disk, restarting the application and then creating tables with certain options.

Here's a quick overview of the steps you need to take, but I'll make sure these are properly documented in the README and HexDocs:

```elixir
# The nodes where you want to persist
nodes = [ node() ]

# Create the schema
Memento.stop
Memento.Schema.create(nodes)
Memento.start

# Create disc copies of the table
Memento.Table.create!(YourTable, disc_copies: nodes)
```

This just needs to be done once to create the disk schema. See the sample implementation in [Que](https://github.com/sheharyarn/que/blob/dc3764a27f8ce3e28b15a7bfafbca604fb424ecb/lib/que/persistence/mnesia/mnesia.ex#L90-L108).

**Comment by yokujin** [comment]
Yeah! Thank you! Got it.
I didn't realize I have to look around schema...

**Comment by yokujin** [comment]
May be it is better to add `disc_copies` option to table definition?

**Comment by sheharyarn** [comment]
> May be it is better to add disc_copies option to table definition?

The Table definition already supports it, but it is recommended that you explicitly pass it when creating the schemas on disk.

**Comment by yokujin** [comment]
How do you pass it to table definition? I tried some different methods and got only errors...

**Comment by yokujin** [comment]
Is it possible to ignore `disc_copies` option when there is no schema created on disk? Or maybe warn about missing disk schema...

**Comment by sheharyarn** [comment]
It is possible and perfectly acceptable. Someone might not want to have all tables be persisted on the disc, only specific ones.

**Comment by sheharyarn** [comment]
> Is it possible to ignore disc_copies option when there is no schema created on disk? Or maybe warn about missing disk schema...

The default behaviour is to raise an exception when trying to create a Table with disc copies when there is no Schema on disk (raised directly from the exit signal thrown by the underlying Mnesia implementation).

**Comment by sheharyarn** [comment]
> How do you pass it to table definition? I tried some different methods and got only errors...

```elixir
defmodule MyTable do
  use Memento.Table, attributes: [:key, :value], disc_copies: [node()]
end
```

Again, this is not recommended at all, and for good reasons:

 - You've now hard-coded the node name, which will be burned into the module at compile-time.
 - You still need to stop and restart the Memento/Mnesia application when creating schemas, and you'll have to specify the node names anyway, making it redundant or causing inconsistent node values in the two functions.

Better to explicitly specify this when you are creating it. You can have a [`setup` function that does it for you](https://github.com/sheharyarn/que/blob/dc3764a27f8ce3e28b15a7bfafbca604fb424ecb/lib/que/persistence/mnesia/mnesia.ex#L90-L108).

**Comment by cpilka** [comment]
OK, the issue was actually http://erlang.org/doc/man/mnesia.html -> "Notice that currently ordered_set is not supported for disc_only_copies". The :bad_type error above was caused by ordered_set in table definition and :disc_only_copies

**Comment by sheharyarn** [comment]
@cpilka Wow that's interesting, I didn't know `disc_only_copies` did not support `ordered_set` tables. I'll make sure that it gets documented in the `create/2` documentation.

Thanks for reporting!

**Comment by sheharyarn** [comment]
As for the flushing the data part, here's a discussion about it on the [Erlang mailing list](http://erlang.org/pipermail/erlang-questions/2006-January/018759.html):

 > With Mnesia using the disk_log module, which in turn usually uses write(2) only, you are not certain that the OS will have copied write(2)'s data to the disk device.  In most cases, the kernel can (and will) wait for many seconds before flushing that data to the disk device.

**Comment by sheharyarn** [comment]
@cpilka's comments moved to a new issue: [Data is not always flushed to disk](https://github.com/sheharyarn/memento/issues/4)
